version: "3.3"
services:
  ip-service:
    build:
      context: ./
      dockerfile: config/prod/Dockerfile
    container_name: ip-service
    volumes:
    - .:/var/www/ip
    ports:
    - 8002:8000
    restart: always

